[package]
name = "lib-hagstrom"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib_hagstrom"
crate-type = ["dylib"]

[dependencies]
hagstrom-km-emulator = { git = "https://gitlab.com/Trustpad/internal-tools/usb2usb" }
lazy_static = "1.4.0"
libc = "0.2.132"
num_enum = "0.5.7"
