[package]
name = "hagstrom_core"
version = "0.1.0"
edition = "2021"
authors = ["xiuxiu62 <jacremer@live.com>"]
license = "Unlicense"

[lib]
name = "hagstrom_core"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
num_enum = "0.5.7"
serialport = "4.2.0"
thiserror = "1.0.33"
